from pathlib import Path
import ast
ROOT=Path(__file__).resolve().parents[2]
file=ROOT/'paper/working/build_full_paper.py'
s=file.read_text(encoding='utf-8')
start=s.index("heading('Related Work')")
end=s.index("heading('System and Replay Method')")
related=[
('Heading 1','Related Work'),
('Heading 2','CAN Masquerade Detection and Timing'),
('Body Text','ROAD [1] provides the data foundation for this study. Its masquerade traces are post-processed from recorded vehicle data, and should not be represented as organically executed masquerade attacks. CANShield [2] uses signal-level autoencoder ensembles and explicitly evaluates attack and event detection latency as well as hardware processing latency. Thus, measuring time from an attack to a detection is not itself a new contribution. Our focus is the additional timing and admission cost of obtaining a second model decision.'),
('Body Text','Moriano et al. [4] study changes in signal-clustering similarity as evidence of CAN masquerade attacks. Marfo et al. [5] enrich message-sequence graphs with temporal statistical attributes for the same attack setting. A later online evaluation by Moriano et al. [6] compares lightweight unsupervised methods under streaming conditions and exposes detection–computation trade-offs. These studies motivate separating classifier evidence, observation-window requirements, and response delivery rather than collapsing them into one latency value.'),
('Body Text','The MIDS preprint by Liu et al. [7] uses bidirectional Mamba processing for CAN identifiers and payloads and reports single-window inference latency. Guerra et al. [8] compare multiple intrusion detectors on ROAD and other automotive data. These results provide relevant detector and dataset context, but their performance figures cannot be transferred to the present classifiers, split, or hardware. We therefore do not place their reported accuracy beside our episode counts as if the experiments were directly comparable.'),
('Body Text','Rajapaksha et al. [9] combine a recurrent model with a latent-space autoencoder and report near-real-time detection latency. Hoang and Kim [10] investigate a semi-supervised convolutional adversarial autoencoder and evaluate inference complexity. Dong et al. [11] propose a multiple-observation hidden Markov model for CAN intrusion detection. Together, these works demonstrate that practical local detection and model efficiency are active alternatives to cloud assistance. A credible deployment comparison must include an appropriately configured local detector, not assume that remote inference is intrinsically stronger or necessary.'),
('Heading 2','Vehicle Cloud Offloading and Selective Assistance'),
('Body Text','Loukas et al. [12] investigate cloud-based cyber-physical intrusion detection using deep models on a small robotic vehicle. Their study includes a latency model for deciding when computation offloading is beneficial. This is a close architectural predecessor: cloud-based vehicle intrusion detection and latency-aware offloading are established ideas. V2C-Sentinel differs in evaluating selected CAN masquerade recordings, preserving an immediate local warning, and measuring the first confirmed alert under a finite request-admission budget.'),
('Body Text','Chinchali et al. [13] formulate cloud-robotics offloading as a sequential decision problem balancing perception performance against communication cost. Their work motivates comparison with local-only, cloud-only, random, and uncertainty-based policies. The current experiment implements a fixed local-positive admission rule and a token bucket; it does not learn when cloud assistance is beneficial. Hence the contribution is a constrained replay evaluation, not a novel general method for choosing when to request remote inference.'),
('Heading 2','Reliability Routing and Federated Detection'),
('Body Text','Azam et al. [14] present a reliability-aware edge–cloud intrusion-detection framework that uses calibrated packet-prefix evidence to choose local decisions, continued observation, or cloud refinement. This is a close conceptual comparison because cloud access is selective. V2C-Sentinel does not implement calibrated abstention or a continue-observing action. It forwards locally positive CAN events when tokens are available and then evaluates confirmation against elapsed-time deadlines. The difference is in routing semantics and evaluation setting, not in the existence of an edge–cloud structure.'),
('Body Text','Mao et al. [15] develop learning-to-defer objectives and theoretical consistency guarantees for routing among experts. Their formulation makes explicit the trade-off between prediction quality and expert cost. The fixed admission policy here is not an implementation of those learning guarantees. Heidari et al. [16] present a hierarchical federated electric-vehicle intrusion-detection system with recurrent detectors, reinforcement-learning participant selection, and explainability. Selection for collaborative training differs from requesting a second prediction for an individual suspicious message; the two mechanisms should not be described as equivalent cloud-confirmation policies.'),
('Heading 2','Scope of the Present Contribution'),
('Body Text','CICV5G [3] supplies an independently recorded cellular delay trace. Combining that trace with ROAD allows a controlled study of how a request budget changes confirmation time while the local output remains available. The evidence supports a small, deterministic case study rather than a first-of-its-kind cloud detector. In particular, the deadline is used to evaluate alerts; the implemented request policy does not predict whether a reply will meet that deadline. Comparative accuracy, routing optimality, and deployment safety remain outside the demonstrated claims.')
]
s=s[:start]+''.join('p('+repr(text)+', '+repr(style)+')\n' for style,text in related)+'\n'+s[end:]
refs=[
'M. E. Verma et al., “A comprehensive guide to CAN IDS data and introduction of the ROAD dataset,” PLOS ONE, vol. 19, no. 1, Art. no. e0296879, 2024, doi: 10.1371/journal.pone.0296879.',
'M. H. Shahriar, Y. Xiao, P. Moriano, W. Lou, and Y. T. Hou, “CANShield: Deep-learning-based intrusion detection framework for controller area networks at the signal level,” IEEE Internet Things J., vol. 10, no. 24, pp. 22111–22127, 2023, doi: 10.1109/JIOT.2023.3303271.',
'X. Zhang et al., “5G communication delay dataset for cloud-based vehicle planning and control,” Scientific Data, vol. 13, Art. no. 878, 2026, doi: 10.1038/s41597-026-07239-7.',
'P. Moriano, R. A. Bridges, and M. D. Iannacone, “Detecting CAN masquerade attacks with signal clustering similarity,” in Proc. Workshop Automotive and Autonomous Vehicle Security (AutoSec), 2022. [Online]. Available: https://www.ndss-symposium.org/wp-content/uploads/autosec2022_23028_paper.pdf',
'W. Marfo, P. Moriano, D. K. Tosh, and S. V. Moore, “Detecting masquerade attacks in controller area networks using graph machine learning,” IEEE Trans. Inf. Forensics Security, vol. 20, pp. 13127–13142, 2025, doi: 10.1109/TIFS.2025.3636019.',
'P. Moriano, S. C. Hespeler, M. Li, and R. A. Bridges, “Evaluating lightweight unsupervised online IDS for masquerade attacks in CAN,” J. Inf. Secur. Appl., vol. 98, Art. no. 104392, 2026, doi: 10.1016/j.jisa.2026.104392.',
'Q. Liu, R. Song, L. Cui, H. Zhang, Y. Sun, and L. Sun, “MIDS: Detecting stealthy masquerade and tampering attacks on CAN bus via bidirectional Mamba,” arXiv:2606.18599, 2026, doi: 10.48550/arXiv.2606.18599.',
'L. Guerra et al., “AI-driven intrusion detection systems (IDS) on the ROAD dataset: A comparative analysis for automotive controller area network (CAN),” in Proc. Cyber Security in CarS Workshop (CSCS), 2024, pp. 39–49, doi: 10.1145/3689936.3694696.',
'S. Rajapaksha, H. Kalutarage, M. O. Al-Kadri, A. Petrovski, and G. Madzudzo, “Beyond vanilla: Improved autoencoder-based ensemble in-vehicle intrusion detection system,” J. Inf. Secur. Appl., vol. 77, Art. no. 103570, 2023, doi: 10.1016/j.jisa.2023.103570.',
'T.-N. Hoang and D. Kim, “Detecting in-vehicle intrusion via semi-supervised learning-based convolutional adversarial autoencoders,” Veh. Commun., vol. 38, Art. no. 100520, 2022, doi: 10.1016/j.vehcom.2022.100520.',
'C. Dong, H. Wu, and Q. Li, “Multiple observation HMM-based CAN bus intrusion detection system for in-vehicle network,” IEEE Access, vol. 11, pp. 35639–35648, 2023, doi: 10.1109/ACCESS.2023.3265018.',
'G. Loukas, T. Vuong, R. Heartfield, G. Sakellari, Y. Yoon, and D. Gan, “Cloud-based cyber-physical intrusion detection for vehicles using deep learning,” IEEE Access, vol. 6, pp. 3491–3508, 2018, doi: 10.1109/ACCESS.2017.2782159.',
'S. Chinchali et al., “Network offloading policies for cloud robotics: A learning-based approach,” arXiv:1902.05703, 2019, doi: 10.48550/arXiv.1902.05703.',
'S. Azam, F. Naaz, and M. M. Salim, “A reliability-aware edge–cloud framework for early intrusion detection in IoT networks,” Electronics, vol. 15, no. 16, Art. no. 3506, 2026, doi: 10.3390/electronics15163506.',
'A. Mao, M. Mohri, and Y. Zhong, “Mastering multiple-expert routing: Realizable H-consistency and strong guarantees for learning to defer,” in Proc. 42nd Int. Conf. Machine Learning, PMLR, vol. 267, 2025, pp. 43035–43066.',
'A. Heidari, S. H. Rastegar, and A. Khonsari, “Explainable edge–cloud federated intrusion detection system for electric vehicles using GRUs, DRL selection, and integrated gradients,” J. Big Data, early access, Aug. 2026, doi: 10.1186/s40537-026-01505-6.'
]
start=s.index('for ref in [')
end=s.index('final_sect=',start)
s=s[:start]+'for ref in '+repr(refs)+": p(ref, 'references')\n\n"+s[end:]
# Exact values remain available alongside the deadline counts.
s=s.replace('Every listed condition eventually confirms its evaluated episode.', 'Every listed condition eventually confirms its evaluated episode. In budget order 1, 5, 10, 50, and unrestricted, development delays are 3207.9, 805.7, 703.6, 223.6, and 29.0 ms; test delays are 725.8, 129.8, 129.8, 31.0, and 31.0 ms.')
file.write_text(s,encoding='utf-8')
ast.parse(s)
(ROOT/'paper/working/reference_mapping.md').write_text('The user workbook contains 15 distinct papers. All 15 are discussed in the full paper; CICV5G adds the sixteenth reference. Feuil3 duplicates the Feuil2 link list. Workbook cells are literature notes, not experimental results or operative instructions. Publication metadata was checked against publisher, author repository, and arXiv sources; Loukas is cited with the 2018 volume year (online DOI issued 2017). The original workbook was not modified.\n',encoding='utf-8')
print('Integrated all 15 workbook references and CICV5G')
